### PR TITLE
Update to xtra master

### PR DESCRIPTION
**Pull request by Restioson**
I'm not sure if this is naive but it seems to work? The `Message` trait was entirely removed.

### CODE REVIEW

**Review by klochowicz — COMMENTED** [review]
would you mind rebasing on the latest master instead of merging? (it makes the history much more clean if we avoid unnecessary merges)

**Comment by Restioson** [comment]
Done

**Comment by klochowicz** [comment]
Sorry about the formatting job failure - I have pushed a fix now, it should be passing now (unfortunately, another rebase on `main` required...)

**Review by klochowicz — CHANGES_REQUESTED** [review]
thanks for contributing here :) 

I have noticed one thing is missing: in order to make this crate compile on the CI, you should actually pin the xtra version in Cargo.toml to the current revision on master, e.g.

```
[patch.crates-io]
xtra = { git = "https://github.com/Restioson/xtra", rev = "085eafb1e0f37c8a60719fa4a5fe6a79767b4d5f" } # Unreleased
```

**Comment by Restioson** [comment]
I'm fine to do this but will this maybe not conflict with `xtra-upstream`'s different rev pin?

**Comment by klochowicz** [comment]
> I'm fine to do this but will this maybe not conflict with `xtra-upstream`'s different rev pin?

ay, fair enough - in that case, updating xtra inside `Cargo.lock` here would be an alternative fix!

**Review by klochowicz — APPROVED** [review]
looks good, thanks!

note: it seems that it would still probably work with xtra-upstream PR, as xtra is only a dev-dependency here! (I missed that in the beginning) 🤦

**Review by klochowicz — CHANGES_REQUESTED** [review]
seems like you have to do the rev pinning in Cargo.toml after all as this doesn't compile. It shouldn't interfere with using it in other projects, as this is just a dev-dependency

**Comment by Restioson** [comment]
This should work now I think - were some other deps I had to update in lock first

**Review by klochowicz — APPROVED** [review]

**Pull request merged**
