### PR TITLE
Instrument handlers by default

### PR DESCRIPTION
**Pull request by Restioson**
This PR makes the `#[xtra_productivity]` attribute automatically propagate attributes, as well as add `#[instrument]` attributes where missing

### CODE REVIEW

**Review by klochowicz — APPROVED** [review]
awesome, thanks for this one!

**Review by klochowicz — COMMENTED** [review]
could you please add a test to ensure that this compiles? (just like others in `tests/pass` directory?)

**Comment by Restioson** [comment]
How do I make sure that the `tracing` feature is enabled for that test?

**Comment by klochowicz** [comment]
> How do I make sure that the `tracing` feature is enabled for that test?

I will open a follow-up, I've done that locally :)

**Pull request merged**
